[project]
name = "dartmouth_langchain"
version = "0.1.0"
authors = [
  { name="Simon Stone", email="simon.stone@dartmouth.edu" },
]
description = "LangChain components for Dartmouth-hosted models."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "dartmouth-auth",
    "langchain",
    "langchain_community",
    "langchain_huggingface",
    "text_generation",
    "python-dotenv",
]

[project.urls]
Homepage = "https://git.dartmouth.edu/lib-digital-strategies/RDS/projects/dartmouth-langchain"
Issues = "https://git.dartmouth.edu/lib-digital-strategies/RDS/projects/dartmouth-langchain/-/issues"